"""Добавил время создания заказа

Revision ID: f043e0bdbea7
Revises: 9fb5ac7cbc81
Create Date: 2024-09-21 19:57:39.427079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f043e0bdbea7'
down_revision: Union[str, None] = '9fb5ac7cbc81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bank_accounts')
    op.drop_table('orderss')
    op.add_column('orders', sa.Column('date_created', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'date_created')
    op.create_table('orderss',
    sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('cusromer_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('total_amount', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('order_id', name='orderss_pkey')
    )
    op.create_table('bank_accounts',
    sa.Column('account_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('balance', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('account_id', name='bank_accounts_pkey')
    )
    # ### end Alembic commands ###
